### ISSUE TITLE
Move to 2019 IMD for 2020 onwards

### ISSUE THREAD

**Issue by AA-Turner** [the-scouts/incognita#36]
**What problem would this feature solve? Please describe.**
The 2019 IMD dataset has been published (Sep 2019, https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019)

We should calculate IMD deciles with the most relevent data available.

We should also probably calculate 2010-2014 IMD deciles using the 2010 IMD datasets

**Describe the solution you'd like**
Allow multiple IMD rankings and deciles to be loaded for different years. We may have to move beyond relying on the data included in the postcode directory

**Additional context**
https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019
https://www.gov.uk/government/statistics/english-indices-of-deprivation-2015
https://www.gov.uk/government/statistics/english-indices-of-deprivation-2010

**Comment by AA-Turner** [comment]
@ox-baloo for thoughts

**Comment by ox-baloo** [comment]
I think we should just use the 2019 IMD deciles retrospectively. My assumption is that not many of them have changed (though this is an interesting question). I think using multiple ones will confuse people reading the data. In the vast majority of cases I care about which areas currently have a low index of deprivation.

**Comment by AA-Turner** [comment]
> I think we should just use the 2019 IMD deciles retrospectively.

Done!
